### ISSUE TITLE
Support for Nested Locations (Parent/Child relationships)

### ISSUE THREAD

**Issue by chaydock** [mattieserver/netbox-topology-views#538] opened 2024-07-27 01:37 UTC
### NetBox version

v4.07

### Topology Views version

v4.0

### Feature type

Change to existing functionality

### Proposed functionality

At present, if you select to group by location, the boxes that are drawn 

1. overlap one another and can at times make it somewhat hard to view.
2. the boxes don't indicate any acknowledgement of the parent-child relationship for other locations.
3. if a parent location doesn't contain any direct devises, the parent box is not drawn at all.

That said....

1. It would be nice if the boxes would be drawn in a manner that they wouldn't overlap (if that's possible). I know that may force some sites to zoom out a lot, but I think it would be worth the trad off. 
2. It would be nice to have location boxes nested inside of each other to respect their parent-child relationships. 
3. Also, to draw the parent location even if that parent doesn't have any direct devices inside. But, obviously not drawn if its children (and any grandchildren, etc.) are completely devoid of any devices.
4. Totally optional... not sure how useful it would be... but, possibly add a selection option to draw locations that don't have devices??? This would be similar to showing devices that are not connected I guess. I presently don't have a use for it... but, I could see how it might be useful at some point.

### Use case

As an example, a site has a 3-story building with a parent location created for each floor and child locations created for each room on those floors. We'll say that devices are placed only in the individual rooms. With that said, when the topology is drawn with location boxes, there should be a location box for each floor (that does not overlap with any of the other boxes for the other floors), and child location boxes for each room (not overlapping one another), and then the devices inside of each room (assuming the room even has a device... don't draw a location if the location has no devices or child locations with devices).

### External dependencies

None

**Comment by dreng** [comment] 2024-07-27 19:05
Hi,

thank you for your contribution. I guess, you're looking at it from the wrong side. The Plugin filters devices. In fact, you can use the same filter criteria in the "Devices" section in order to get a list of devices that whould be shown in the topology view.

If you have not saved any device coordinates in a coords group, the device positions are calculated by a physics engine (vis-network in our case). Location boxes then follow this calculated icon positions.

The boxes depend on device coordinates and nothing else. Your proposal would first filter locations, let a physics engine calculate the spreading of that boxes without any intersection and add device icons into the boxes after that. Since we use the device filter approach, we would have to re-think and rewrite the whole plugin (with all drawbacks of this approach). As you can think yourself, this won't happen.

Personally I use it like that:
Let's assume you have 5 locations with some infrastructure devices you would like to show in a topology view.

1. Create a new coordinate group and name it e.g. "infrastructure"
2. Go to the filters tab
3. Filter by all 5 locations and certain device roles such as switch, patch panel and anything that belong to your infrastructure
4. Activate options "Show Locations", "Save Coordinates", "Show Cables" and optionally "Show Unconnected" and "Show Logical Connections"
5. Click the search button
6. In the topology view, click the border of a box in order to select all devices that belong to that box
7. Move the selected devices far our of the way and arrange the icons within the box that automatically follows the devices
8. Repeat the last steps for other location boxes
9. Optionally save the filter for later use

**Comment by chaydock** [comment] 2024-07-28 03:04
Thanks for the feedback. And, I don't want this to come off as argumentative... but, it's going to come off that way no matter how I say it.... so... here goes...

I would take a position that what I am asking for is not an incorrect use of the functionality of locations as you suggest. The way you are describing a "location" as being strictly tied to a GPS coordinate, I would propose is more of a "site" than a "location" function and a "nice to have" for locations. My stance would be further justified that locations have a parent-child relationship. And, why would you stipulate that a location is nothing more than a GPS coordinate and then go on to create a parent-child relationship for them? Going even further... locations are associated with a site. Now... I'll happily concede that within a "very large site" that you could have a sprawling number of buildings or equipment utility boxes and the like... each of which could be their own "location" within a "site"... and it would be helpful to have GPS locations for each of those buildings. But, again, locations belong to sites... and locations support a nested parent-child relationship. So, even if you say you have a "Site A" with a given GPS coordinate (we'll say for the main entrance or something)... and within that site you have 5 different buildings.... "Locations" associated with that site... each of which could have a GPS coordinate... those locations could have child locations such as each floor of the building, and those child locations could have grandchildren for rooms within those floors.... and those rooms could have great-grand-children to indicate equipment cages within a room (e.g. at a datacenter). This could go on-and-on-and-on for as far as could be imaginable. And, beyond the initial building location at a site having a GPS location, any floor location or room location as a child would be optional at best as assigning one might not have any benefit and could even cause grate confusion if it's a multi-floor building.

In any case... I tried your method on a particular set of locations at a site... short of assigning any GPS coordinates as it would be impractical to affix a GPS position for a room inside of a small-ish building... especially as some rooms would be on top of one another in a multi-floor building. In the end... what was drawn following your method are a series of devices that are connected as per usual with boxes surrounding clusters of associated devices. The boxes themselves overlap each other quite heavily... **and some of them are even completely inside of another location box even though they do not have a parent child relationship**. In short... nothing changed from my normal experience up to this point. Continuing on though... I'm unable to grab ahold of just the location bounding box to move a single location. Grabbing a box boundary or the name of a location simply moves the entire render of devices as a single unit. I can however grab an individual device inside of a box and move it around... and the location box will scale if needed and follow that set of devices.... but, it will also immediately snap back to wherever it feels like rather than staying put. If there's an option to turn off the auto-snap/redraw/reposition of the render... I've not seen that toggle switch (that's actually something I would also like to see... but that' should be its own feature request).

As for your comment about having to re-engineer the way the system searches and renders everything... I would disagree. You are still primarily searching for and filtering for devices and any connections they have. And, just like you are now, finding out which locations they are associated with. All of that I would presume should stay unchanged. What I'm asking for is that once the individual locations are captured that they 1) be drawn in a non-overlapping manner (because right now they just overlap however they feel like it). 2) that if they have a parent location that the parent be drawn as well (because right now the parent isn't drawn unless there also happens to be a device in that parent.... and even then, the parent devices is being drawn as an independent box and doesn't show any type of relationship to any of the other boxes). 3) groups of children are appropriately grouped in a shared parent... is redundant to #2 and should go without saying... but this is just emphasizing the fact that at present the location boxes do not show _any_ parent-child hierarchy/relationship.

The only part that would possibly require any kind of re-engineering of code would be if you offered up the suggested optional suggestion of drawing locations that are empty of any devices or child locations that lack devices.... essentially just an empty box. But, even that shouldn't be an end of the world query to implement. It should just be a side-branch of code to run an additional query. And, just to restate... it was an optional requested item anyway. The main focus is first and foremost to not have location boxes overlap each or even be drawn inside of each other when there's absolutely no parent-child relationship between them... and then actually do draw them inside one another to honor the real parent-child relationship that does exist. Anything above and beyond that is "frosting on the cake." So, if you care to scrap that part of the request... feel free. I won't cry.

Anyway... I know that's going to be taken as argumentative. My apologies. But, I want to take another swing at explaining this as a situational example. So, let's open this up all the way and even expand a bit... Say I have 5 sites and some of those sites have multiple buildings, and some of those buildings have multiple floors, and within any given floor there are often times multiple rooms. Now... as for the search filters... I say I want sites to be grouped and locations to be grouped... for sake of argument I don't set any other filter restrictions... just draw every device there is to draw. _**What I would expect**_ is a red site bounding box for each site that has a device... that red site box should NOT overlap with any of the other sites (the issue is also with sites if you haven't noticed yet). Within that red site box are the blue location boxes... there should be a location box for each building that has a device in it. If there are multiple building locations drawn... none of those boxes should overlap one another. Within the building boxes, there may be multiple floor boxes drawn (assuming there are devices on multiple floors)... and none of the floor boxes should overlap. If there are multiple rooms within a floor that have devices within them... multiple room location boxes would be drawn... again... non-overlapping. **All of this behavior is to honor and accurately represent the parent-child relationship.** I hope that helps as an example of what's being requested. If it's still unclear... let's try to find a way to do a video chat so I can better show and explain this request.

**Comment by chaydock** [comment] 2024-07-28 03:28
Here's a squinty example of a semi-filtered device search that results in a jumbled and essentially non-usable mess...

![TopologyMess2](https://github.com/user-attachments/assets/6bb6c1ed-66c0-45ca-9aae-34fde6f358b4)

Sorry for it being so squinty... I just zoomed it out far enough to sufficiently blur the labels instead of dropping it into photoshop and editing out each device label. Anyway.... As you can see (hopefully) in that picture is that many of the boxes overlap each other in ways that make it unclear in some cases which box a device belongs inside of. And, other than the location boxes being bound inside of their appropriate site boxes... none of the location boxes honor the parent-child relationships they have with each other.

Maybe I'm missing the mark on some setting that magically de-clutters this mess. If it exists... I haven't found it if it exists though. <shrug>

**Comment by chaydock** [comment] 2024-07-28 04:07
Wanting to make sure I wasn't making a fuss over something that might have been fixed. Even though I didn't see any mention of anything dealing with this issue in any of the update release notes... I upgraded Netbox from 4.0.7 to 4.0.8 just out of caution. (Topology Views is still at 4.0.0.), I then re-ran the same filter/query as was used for the previous screen shot to see if any behavior changed and comically enough, what it spits out is now actually even worse than before. I have no idea why... maybe it's returning objects in a different order which effects the way/order that they are then in turn rendered??? In any case, for what it's worth, it's repeatable to get this same result....

![TopologyMess3](https://github.com/user-attachments/assets/1c7a586e-8a65-476e-a397-5e32d2fa17db)

In this view you can see that two of the site boxes are so heavily overlapped that there is more overlapped area between them than non-overlapped area! Again... maybe I'm a moron on how I'm using this and missing a setting that changes this behavior. <shrug> But, as it stands now, asking Topology Views to "Group Sites" and/or "Group Locations" is a broken function for me.

**Comment by chaydock** [comment] 2024-07-28 04:51
Having shown the above pictures with the site boxes... that got me to thinking.... **Site Groups and their parent-child relationships**. So, I did a quick test of "Group Sites" where 1) there is a parent site group that has multiple child site groups.. And, 2) within those child site groups, at least two of them have multiple child sites (to wrap your head around this... think of a university that has multiple regional areas, and some of those areas have either multiple disjoined campus locations, and/or campus locations with multiple buildings spread over multiple city blocks... each building is listed as a site with a physical mailing address and all that jazz.)

Anyway... As I suspected... since I assume it's using the same rendering engine to determine placement... the site boxes also fail in the same manner as the location boxes. They do not show a parent site group box or any sibling relationships to one another. And, of course, they are drawn overlapping each other in peculiar ways. To be fair though... the filter options do not say anything about "Group Site Groups" or anything like that.... it's just "Group Sites". So... maybe "Group Site Groups" is worthy of another filter selection option??? But, as the code change for this is probably the exact same as is needed to resolve the issue with the location boxes... I just thought I would mention it here in case you are feeling ambitious. ;)

**Comment by chaydock** [comment] 2024-07-28 08:23
OK... So... I have to eat a little crow here. I kept plugging away at this and re-read your reply multiple times thinking that I must be missing something here... and I was indeed. So, I apologize for not having caught this the first go around. (and hence why I deleted the previous comments) What happened is that I didn't have it set to **save coordinates** thinking at first this was with respect to GPS coordinates or something and not the Topology Views canvas rendering coordinates. So, with that fixed... now devices at least lock in place once they are moved and don't snap back like before. Also... After fiddling with what you stated about clicking and moving the box... I eventually figured out that after clicking the box you don't try to drag the box itself, but rather click on one of the devices within the box to move the collection of devices all at once (which in turn moves the box). I can now manually reposition them so that they don't overlap one another. And that alone is a HUGE victory. So, thank you.

All that said... there's still the main issue at hand that prompted me to open this feature request... there is absolutely zero parent-child relationship for locations... or for sites... that are being represented. So, at present, the way the location boxes appear to be derived is simply if a device is within that location and a box is drawn around it. There's enough additional code to draw all devices that share the same location box into a single box. However, that's where the code appears to stop. So, what could/should be done to resolve this is to look if that location box has any parent locations associated to it and tally those up and draw all of them too. If multiple location boxes share the same parent... then the location boxes should be nested inside that parent box. Since this functionality already appears to be present in the sense that all location boxes for a site are grouped inside the site box (the same happens for multiple racks in a single location)... and the site box seems to dynamically resize to keep all child location boxes inside its boundaries (and the location box will resize to keep all the racks inside the box)... I don't anticipate that this would be a huge revamping of the code... just an extra recursive layer of searching for and combining any parent boxes. I say recursive only because I don't know of any limits at present for how many levels deep that locations are allowed to have a parent-child relationship with. I've already tested to 3 layers deep (building>Floor>room)... but, I don't know how far one can actually go before something breaks in NetBox. <shrug> On a good note though.. Netbox does appear to honor a strict one to many relationship that does not allow for loops to be created (e.g. a grandchild being listed as the parent of it's grandparent). I've tested by trying to set the building location as having a parent of one of the rooms and when you click save it throws an error stating "Cannot assign self or child location as parent." That said... any recursive search function shouldn't find itself stuck in an endless loop.

Technically... This same change could take place with sites and "site groups" too. But, an explicit option for "Group Site Groups" doesn't presently exits. To me, the option of "Group Sites" rather implies that site groups should therefore be rendered too IMHO. That said, I'm not sure if you would want me to take that up as an independent feature request or address that all here within this one? Your call I guess.

**Comment by dreng** [comment] 2024-07-28 16:03
> I eventually figured out that after clicking the box you don't try to drag the box itself, but rather click on one of the devices within the box to move the collection of devices all at once (which in turn moves the box).

I agree that this is not intuitive. Problem is, that the drag function is part of the vis-network physics engine. The boxes itself are part of our own code. It wouldn't be impossible to implement an own drag function but I think that it would be tedious work for a relatively small benefit. But if someone would like to take work on it...

Regarding your proposal: If I understand correctly you propose to add location boxes for parent locations. While I understand your intention, I don't find it logical. The logical way is to do it the other way round and that's how it is implemented. The same logic applies for devices in general. If you filter devices by location with a high level, all devices in nested locations will be included recursivly. Following your logic, we would filter devices by a child location and all devices in parent locations would be included. Obviously, that's not the case.

Generally speaking I tend to follow the logical concepts of NetBox. The topology view should always be a visual equivalent of the textual display. Otherwise, we risk developing against NetBox, which may lead to incompatibilities and high programming effort.

**Comment by chaydock** [comment] 2024-07-29 14:48
I think you are perhaps misunderstanding the request. Maybe I'm stating it wrong? Or, maybe I'm the one mistaken on understanding how the current engine works to understand how this is some earth-shattering change. But, let's try this one more time. Here's a current situation....

I have a site ("Site A") that has a main office building ("Main Building") as well as a detached garage ("Garage") on the property. A location is created for both the Main Building and Garage. That Main Building location has a device that is assigned to it at that location level... for this example we'll say it's a piece of the ISP demark equipment or something that was bolted on the outside of the building. The building itself is a single-story building with a basement. So, a location was created for each floor as a child to the building location ("Basement" and "1st Floor"). In the Basement is another piece of ISP equipment... a fiber splice box or something that's bolted on the wall. Off in the corner of the basement, a small room is framed in and considered the main "IT Closet"... a location is created for that room and is a child location to the Basement location. In that room we have a UPS sitting on the floor and is thusly assigned to the room location. There's also a small 24U rack ("Rack") with all the building's IT equipment inside (firewall, switch, server, etc.). On the first floor, in the office conference room is a single Wi-Fi access point. That room is created as a location ("Conference Room") and is a child to the 1st Floor location. Circling back... that detached Garage is just one big open space, is a single floor, and has a Wi-Fi access point as well... which is simply assigned to the building location.

To this point we would have the following structure and parent-child relationships:
- Site - "Site A"
  - Location 1 - "Main Building" - Main parent location to the building floors
    - Device - ISP equipment bolted to outside of building
    - Location 1(a) - "Basement" - Child to Location 1
      - Device - ISP Fiber Splice Box
      - Location 1(a)(1) - "IT Closet" - Child to Location 1(a)
        - Device - UPS
        - Rack - "Rack"
          - Device - Firewall
          - Device - Switch
          - Device - Server
    - Location 1(b) - "1st Floor" - Child to Location 1
      - Location 1(b)(1) - "Conference Room" - Child to location 1(b)
        - Device - Wi-Fi access point
  - Location 2 - "Garage"
    - Device - Wi-Fi access Point


So, I now run a query in Topology Views to show me all the equipment at that site and ask it to group sites, locations, and racks. Well... the way Topology Views is currently implemented... there would be a single red box for the site. So far so good. Inside that site would be multiple blue boxes for each Location that has a device assigned to that location. So, we would see a box for locations 1, 1(a), 1(a)(1), 1(b)(1), and 2.... 5 location boxes... even though there are actually 6 locations (more on that in a bit). **These location boxes are drawn as their own independent boxes and do not show any relationship to one another**. And there would be a single green box for the rack that is properly nested inside the IT closet (Location 1(a)(1)) box.

If we move the equipment inside any of these location boxes around, the box itself will move to follow it... but, again, the location boxes themselves have no relationship to each other and will move independently of each other (this is undesirable). By contrast, if the equipment is moved far enough, the Site box will resize itself and scale as needed to contain all the location boxes inside (This is desirable). Similarly, if we move the equipment inside of the rack around, the rack box itself scales/resizes to ensure it contains all the equipment... AND... the location for the rack will also resize/scale to ensure the rack box stays within the location box (both of which are desirable behaviors).

All that said, rather than the proper parent-child relationship as shown in the previous list above, you more or less end up with a rendering that has a hierarchy that looks like this...

- Site - "Site A" (red box as a parent to locations)
  - Location 1 - "Main Building" - Child to Site A
    - Device - ISP equipment bolted to outside of building
  - Location 2 - "Basement" - Child to Site A
    - Device - ISP Fiber Splice Box
  - Location 3 - "IT Closet" - Child to Site A and parent to Rack
    - Device - UPS
    - Rack - "Rack" - Child to Location 3
      - Device - Firewall
      - Device - Switch
      - Device - Server
  - Location 4 - "Conference Room" - Child to Site A (note that the parent location of 1st Floor is not drawn)
    - Device - Wi-Fi access point
  - Location 5 - "Garage"
    - Device - Wi-Fi access Point

What I'm asking for in this feature request is that similar to how the boxes for locations are clearly given a proper parent-child relationship to the site... and the equipment rack is clearly given a parent-child relationship to the location... please, Please, PLEASE honor the parent-child relationship for locations to each other. Start drawing location boxes inside of other location boxes if one location box is a child to the other. And if/when that box is resized, force the parent box to resize as needed to continue to contain that child box.

Second on the wish list.... In the above example, the 1st Floor location box was never drawn because it did not contain any direct child devices... only a child location... the conference room... which incidentally had a valid device to be drawn. What I'm asking for is that if any locations are drawn because they contain a device... check to see if that location is a child to another location... and if so, draw that location too as a parent.

What I am NOT asking for (at this time) is to simply draw every location available regardless of devices being drawn (i.e. drawing empty location boxes). I could see a use case for this. But, it's beyond the needs of the main point of this request.

So... with all of that said... There's obviously pre-existing code that's in play for creating the parent-child relationship from Site to Locations... and I presume it's the same code that honors the parent-child relationships between locations and racks. So, just reuse that same code to enforce parent-child relationships from Locations to Locations. Second to that... there would be some new code that would need to be added that checks for the existence of a parent location and to draw said parent even if that parent is otherwise empty of devices that have been filtered for rendering. And, as the number of parents/grandparents/great-grandparents would be unknown... the search for parents would thus have to be a recursive search to identify and draw all parents up the chain/tree. This should only be an upward search for parent objects though. The only reason to look downward for child locations would be if you wish to enable additional functionality to draw empty locations (similar-ish to the option of saying you want to draw unconnected devices).

In total, I don't see this being a monumental task. it should not require a huge amount of code, nor a complete re-work to how any existing features are implemented. This should reuse some of the existing code already in play for parent-child relationships. And, a small addition of code to identify parent locations that would otherwise have gone un-drawn.

I also want to touch on something you stated in your response... " all devices in parent locations would be included" ... I'm NOT asking to have devices drawn that would have otherwise been filtered by the search simply because the location is being drawn. Far from it. I'm not asking for any additional devices to be drawn. Only that additional location boxes be drawn... and only if those locations are parents to other locations that are already being drawn because of the filtered devices. As an example of this using the above equipment scenario presented. Say we do a filter for that site to only show the Wi-Fi access points. The way Topology Views would currently render this would look as follows:

- Site - "Site A" (red box as a parent to locations)
  - Location 1 - "Conference Room" - Child to Site A (the parent locations of 1st Floor and Main Building are not drawn)
    - Device - Wi-Fi access point
  - Location 2 - "Garage"
    - Device - Wi-Fi access Point

What I would expect instead with the proposed implementation would be as follows:

- Site - "Site A"
  - Location 1 - "Main Building" - Main parent location
    - Location 1(a) - "1st Floor" - Child to Location 1
      - Location 1(a)(1) - "Conference Room" - Child to location 1(a)
        - Device - Wi-Fi access point
  - Location 2 - "Garage"
    - Device - Wi-Fi access Point

So, as you can see... the list of devices drawn stays unchanged. But, the parent-child relationship query would look upstream to the Conference Room location and subsequently draw the 1st Floor and Main Building location boxes in a nested manner that honors their relationships.

Hopefully this is clearer on what I'm asking for. I don't believe what I'm asking for will in any way break or dishonor the structure of NetBox. If anything, I believe what I'm asking for is actually a more accurate representation of what NetBox has within its structure considering the parent-child relationship of locations is a native feature of NetBox. If anything... I would take up the position that the current implementation of Topology Views rendering of locations is a disservice to the native structure of NetBox as it ignores the parent-child relationship of locations.

**Comment by chaydock** [comment] 2024-07-29 15:35
Thinking about the last paragraph in my previous comment... the fact that the current implementation of Topology Views does not honor the parent-child relationship of locations as a core implementation of the NetBox architecture. I'm half inclined to ask if the label for this thread could be changed from "Feature" to "Bug" instead. <shrug> I'm not asking to implement something that's outside of the scope of core NetBox capability... to fabricate something new and unique to Topology Views as a "value add". I'm asking to fix an inaccurate representation of the core NetBox object relationships. Which... thinking about it... would really be a bug fix, would it not?

**Comment by dreng** [comment] 2024-07-29 22:48
Wow, that's a... errr... huge text... :-) A few screenshots would have helped a lot more.

I created the mentioned locations and devices in my dev environment and this is what it looks like:

Locations, filtered by Site A:
![SiteA_Locations](https://github.com/user-attachments/assets/1537895b-bd33-4b42-9714-2f892dfc0962)
Devices, filtered by Site A:
![SiteA_Devices](https://github.com/user-attachments/assets/235aa9f5-f24e-49d8-bf2c-f9fd25c02f1f)
Topology, filtered by Site A:
![SiteA_Topology](https://github.com/user-attachments/assets/cd9a8a37-cace-4756-9e1b-8c29d7b96427)

The device list shows all information we have got to work with.
As you can see, the topology corresponds to the filtered device list. This is how it's intended. There are only 5 different locations in the device list although there are 6 in the location list. There is no relationship between the listed locations in the device list (regarding their parent locations). If you think that's wrong or incomplete, I suggest to complain about the situation upstream.

Again, we don't (and don't intend to) draw a hierachical view of locations. Instead we just draw devices. The grouping functions just group devices that belong to the exact same location.

> I'm half inclined to ask if the label for this thread could be changed from "Feature" to "Bug" instead.

And I'm half inclined to convert this thread into a discussion. You think that your point of view is correct. I don't. It's definitely not a bug, because it works as intended.

> I'm asking to fix an inaccurate representation of the core NetBox object relationships.

If upstream supports your point of view and changes the representation, we will follow.

**Comment by chaydock** [comment] 2024-07-30 01:36
> Wow, that's a... errr... huge text... :-) 

Sorry. I have a propensity to be verbose. It's a curse.

> The topology view should always be a visual equivalent of the textual display.

To that end... and even by your own screenshots... Topology Views are **not** honoring the visual text display since the locations themselves within the list are honoring a parent-child hierarchy. (see below screen shot with the single and double dots indenting the location name to indicate that it is a child item. For what it's worth... this same indent technique is used under Site Groups as well.... which Topology Views also doesn't represent/depict.).

![image](https://github.com/user-attachments/assets/b37c4df3-8408-4465-b293-d9fd28ecf8c8)

 Topology Views at present only partially honors the full hierarchy within Netbox. It honors the fact that the locations belong to a site... and it honors the fact that racks belong to a location. But, it does not honor that locations have a parent-child relationship too.

As for a picture "to tell a thousand words"... after fiddling around a bit in Photoshop, I mashed together something that resembles what it would/could/should look like if the parent-child hierarchy is fully honored...

![NetBox-Locations-With-Hierarchy](https://github.com/user-attachments/assets/50cf9874-1b06-434c-8ec5-f30ddd8bf7cc)

granted... placement in the objects in the picture isn't fantastic. This isn't an art contest after all. ;) I just quickly mashed that together. The point is though... **visually**... it is an accurate representation of the hierarchical structure of Sites>Locations>Racks with a full representation of the parent-child relationships of all the locations.

And... Since it's been mentioned more than once... and you wanted pictures... Here goes as it comes to Site Groups... which suffers from the same issue as Locations. Here's a test I created of Site Groups and associated test sites....

![Site-Groups-Test-Text-List](https://github.com/user-attachments/assets/fde078f2-04f4-4770-9c4a-c13e5c450b96)

Please take note of the fact that Site Groups use the very same dot notation in front of their name to indicate a nested parent-child relationship/hierarchy. Now... going into Topology Views and asking it to show the site group "Major University" and to "Group Sites" dumps out just a non-relationship rendering of the sites...

![Sites-Not-Grouped](https://github.com/user-attachments/assets/7a108787-da87-4466-81a2-cd3cadf7dc79)

I tried to keep the above image as clean and simple as I could by only adding a single device at a site without any locations or racks. I trust you can let your imagination fill in the details of having much more inside each site box.

Using some PhotoShop magic... this is what the render would/should/could look like if the Site Group hierarchy would have been honored...

![Sites-Grouped](https://github.com/user-attachments/assets/9d446410-1dc7-4b0e-8010-5bf0bcbbd8c8)

I only bother to mention the Site Groups part here because I can only presume that whatever the fix for Locations will be a very similar if not identical fix for Site Groups.

> If upstream supports your point of view and changes the representation, we will follow.

Point me to whomever you wish and I will gladly state my case to them. Although... I would like to point out the part about "...changes the representation..." and "The topology view should always be a visual equivalent of the textual display.".... I think it has already been established with the screenshots (that even you yourself provided) showing that the indented dots in the list represent a child status. So... \<shrug\>... Let me know how you want to proceed. Again... I'm happy to talk to whomever is needed to set this straight.

**Comment by chaydock** [comment] 2024-07-30 14:32
Just a little something extra... In addition to the dot notation in the text view of the site groups... take note of the number of sites listed for each site group. The numbers shown add up to their respective parent in that list. Which in its own way is further reinforcement of the parent-child relationship hierarchy that exists. Running through the math.... So Cal (3) + No Cal (2) = Cal Schools (5)... and Cal (5) + Flor (2) + NY (1) = Maj Univ (8).

The same happens in the list of Locations and device count. But it's a bit tricky since some devices are assigned directly to a location in addition to the devices located in child locations under that specific location. But... if you look at your table of locations, and then look at my PhotoShop representation of how it could/should be drawn... the numbers in that table add up exactly as shown. For example... the IT Closet is showing 4 devices... the UPS directly assigned to the location plus the 3 devices in the rack. The Basement location shows 5 devices... the 4 in the IT closet plus the one Fiber Splice Box device assigned directly to the Basement location. So on and so on until you get to the site level for a total of 8 devices for the site (1 in the garage and 7 in the main building).

So... as it pertains to your previous statement of

> The topology view should always be a visual equivalent of the textual display.

I think that the mathematical summaries as textually displayed is just one extra reason why nested location and site boxes need to be drawn to accurately represent the true parent-child hierarchy relationships as depicted in the text displays for both Locations and Site Groups. The addition of these boxes will show the nature of how these numbers are derived.

**Comment by dreng** [comment] 2024-08-13 12:35
> Again, we don't (and don't intend to) draw a hierachical view of locations. Instead we just draw devices. The grouping functions just group devices that belong to the exact same location.

^^^
This!

**Closed as completed** 2024-08-13 12:35 UTC
Labels: type: feature, status: wontfix
