### ISSUE TITLE
Feature Request: Virtual Machines?

### ISSUE THREAD

**Issue by allenc125789** [mattieserver/netbox-topology-views#402] opened 2023-10-12 18:25 UTC
### NetBox version

v3.6.3

### Topology Views version

v3.7.0

### Feature type

New functionality

### Proposed functionality

I wanted to find out if there are any plans or if adding the option to list Virtual Machines to the Topology plugin was being considered?

Along with the ability to segment zones by locations, not being able to list my Virtual Machines is a big problem that might put a stop on me being able to truly use this plugin.

### Use case

Being able to list Virtual Machines will help:
- Accurately gauge network size and capacity of maps housing VM's
- List what IP's are assigned to VM's
- Visually show that essential services are running within a physical server's hypervisor

Often we need to show a network map to other's who need to understand how our infrastructure runs. Not being able to show Virtual Machines hinders what someone looking at these maps can comprehend from it.

**Comment by dreng** [comment] 2023-10-13 09:20
Duplicate of #51

**Closed as not planned by dreng** 2023-10-13 09:20 UTC
Labels: type: feature
