### ISSUE TITLE
Exception during upgrade 3.7.0 with plugin enabled

### ISSUE THREAD

**Issue by wannagofast83** [mattieserver/netbox-topology-views#441] opened 2024-01-04 22:03 UTC
### NetBox version

3.7.0

### Topology Views version

3.8.1

### Steps to Reproduce

Upgrade process to Netbox to 3.7.0, with topology view enabled. Upgrade completed after I disabled the plugin.

### Expected Behavior

Successful upgrade 

### Observed Behavior

`ImportError: cannot import name 'WebhooksMixin' from 'netbox.models.features' (/opt/netbox/netbox/netbox/models/features.py)
Jan 04 14:28:14 netbox-test gunicorn[2304611]: [2024-01-04 20:28:14 +0000] [2304611] [INFO] Worker exiting (pid: 2304611)
Jan 04 14:28:14 netbox-test gunicorn[2304602]: [2024-01-04 14:28:14 -0600] [2304602] [ERROR] Worker (pid:2304611) exited with code 3
Jan 04 14:28:14 netbox-test gunicorn[2304602]: Traceback (most recent call last):
Jan 04 14:28:14 netbox-test gunicorn[2304602]:   File "/opt/netbox-3.7.0/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 209, in run
Jan 04 14:28:14 netbox-test gunicorn[2304602]:     self.sleep()
Jan 04 14:28:14 netbox-test gunicorn[2304602]:   File "/opt/netbox-3.7.0/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 360, in sleep
Jan 04 14:28:14 netbox-test gunicorn[2304602]:     ready = select.select([self.PIPE[0]], [], [], 1.0)
Jan 04 14:28:14 netbox-test gunicorn[2304602]:   File "/opt/netbox-3.7.0/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
Jan 04 14:28:14 netbox-test gunicorn[2304602]:     self.reap_workers()
Jan 04 14:28:14 netbox-test gunicorn[2304602]:   File "/opt/netbox-3.7.0/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 530, in reap_workers
Jan 04 14:28:14 netbox-test gunicorn[2304602]:     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
Jan 04 14:28:14 netbox-test gunicorn[2304602]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
Jan 04 14:28:14 netbox-test gunicorn[2304602]: During handling of the above exception, another exception occurred:
Jan 04 14:28:14 netbox-test gunicorn[2304602]: Traceback (most recent call last):
Jan 04 14:28:14 netbox-test gunicorn[2304602]:   File "/opt/netbox/venv/bin/gunicorn", line 8, in <module>
Jan 04 14:28:14 netbox-test gunicorn[2304602]:     sys.exit(run())
Jan 04 14:28:14 netbox-test gunicorn[2304602]:   File "/opt/netbox-3.7.0/venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
Jan 04 14:28:14 netbox-test gunicorn[2304602]:     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
Jan 04 14:28:14 netbox-test gunicorn[2304602]:   File "/opt/netbox-3.7.0/venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 236, in run
Jan 04 14:28:14 netbox-test gunicorn[2304602]:     super().run()
Jan 04 14:28:14 netbox-test gunicorn[2304602]:   File "/opt/netbox-3.7.0/venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 72, in run
Jan 04 14:28:14 netbox-test gunicorn[2304602]:     Arbiter(self).run()
Jan 04 14:28:14 netbox-test gunicorn[2304602]:   File "/opt/netbox-3.7.0/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 229, in run
Jan 04 14:28:14 netbox-test gunicorn[2304602]:     self.halt(reason=inst.reason, exit_status=inst.exit_status)
Jan 04 14:28:14 netbox-test gunicorn[2304602]:   File "/opt/netbox-3.7.0/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 342, in halt
Jan 04 14:28:14 netbox-test gunicorn[2304602]:     self.stop()
Jan 04 14:28:14 netbox-test gunicorn[2304602]:   File "/opt/netbox-3.7.0/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 396, in stop
Jan 04 14:28:14 netbox-test gunicorn[2304602]:     time.sleep(0.1)
Jan 04 14:28:14 netbox-test gunicorn[2304602]:   File "/opt/netbox-3.7.0/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
Jan 04 14:28:14 netbox-test gunicorn[2304602]:     self.reap_workers()
Jan 04 14:28:14 netbox-test gunicorn[2304602]:   File "/opt/netbox-3.7.0/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 530, in reap_workers
Jan 04 14:28:14 netbox-test gunicorn[2304602]:     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
Jan 04 14:28:14 netbox-test gunicorn[2304602]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
Jan 04 14:28:14 netbox-test systemd[1]: netbox.service: Main process exited, code=exited, status=1/FAILURE
Jan 04 14:28:14 netbox-test systemd[1]: netbox.service: Failed with result 'exit-code'.`

**Comment by WombatTurd42069** [comment] 2024-01-04 22:55
Are you using correct plugin version (3.9)?

Try:
`pip install netbox-topology-views==3.9b1 --upgrade`

**Comment by dreng** [comment] 2024-01-05 07:12
Duplicate of #430 , which is fixed already.

**Closed as completed by dreng** 2024-01-05 07:12 UTC
Labels: type: bug, status: duplicate
