### ISSUE TITLE
Sites -> Topology show devices without connection cables

### ISSUE THREAD

**Issue by fafavorit** [mattieserver/netbox-topology-views#237] opened 2023-01-05 16:03 UTC
### NetBox version

v3.4.2

### Topology Views version

v3.2.0

### Steps to Reproduce

Click on Sites -> Topology

### Expected Behavior

I expect to see all devices in the site connected with cables. 

### Observed Behavior

I can see all devices in the sites but without connection cables.

**Comment by dreng** [comment] 2023-01-06 06:56
This is not a bug as it works as intended. You have to tick the checkbox for cables if you want to see them. We can discuss if that checkbox should be ticked as a default. That would be a feature request then. Otherwise please explain what exactly you consider a bug. Furthermore the steps to reproduce you provided do not fit the observed behavior. In fact, I see an emtpy canvas if I follow your steps.

**Comment by fafavorit** [comment] 2023-01-06 07:10
I can see the following. There is no way how to enable show cables. (or I can't see it)
<img width="1436" alt="Screenshot 2023-01-06 at 8 04 52" src="https://user-images.githubusercontent.com/37589981/210949049-5ded4f0a-06b6-4c52-b9c1-24d5e66e347b.png">

**Comment by mattieserver** [comment] 2023-01-06 07:46
Do the cables connect directly to the devices seen on the topology or are there any patch panels/other devices in the 'path' of the cable?

**Comment by fafavorit** [comment] 2023-01-06 08:10
It is directly connected. Here is how it looks like in plugin with enabled show cables.
![topology (3)](https://user-images.githubusercontent.com/37589981/210957951-786f57f0-b6a0-463b-8d02-64b98f5440ed.png)

**Comment by dreng** [comment] 2023-01-06 08:19
My bad. I didn't read your steps carefully. I apologise. This is a bug indeed.

**Comment by dreng** [comment] 2023-01-06 16:09
Gladly, this fix is a one-liner. In your opinion, should we just show cables or cables as well as end-to-end connections? You may consider that I just tested both in my test environment. Enabling cables AND end-to-end connections took about 170% more time to calculate than just enabling cables. Calculating a whole Site may take some time.

**Comment by fafavorit** [comment] 2023-01-06 17:09
For me cables are fine :) But maybe somebody have different point of view. Recalculating time is not problem for me as I usually have only a few devices per site.  I don't know if there is a possibility to have check boxes for modification.Thank you for your great job!

**Comment by fafavorit** [comment] 2023-01-09 14:05
I'm not sure if I got you right. I tested new version and connections are visible now! Thanks for it! There is no visibility of details of connection (from which device/interface it is connected to which device/interface) And here I'm afraid that you was asking if it is needed and I didn't understand it. It will be great if there will be this information. Sorry for misunderstanding :/

**Comment by dreng** [comment] 2023-01-09 15:11
No worries! I wasn't asking about connection details. The question was if you need end-to-end connections (the yellow lines that you can enable by checking logical connections). Since site view came with a merged PR, I can not tell why the information popup windows has been left out. That would be a new feature request then.

**Closed by dreng** 2023-01-09 15:11 UTC
Labels: type: bug, status: accepted
