### ISSUE TITLE
Display device labels on top of logical connections

### ISSUE THREAD

**Issue by royvegard** [mattieserver/netbox-topology-views#253] opened 2023-01-28 21:32 UTC
### NetBox version

v3.4.3

### Topology Views version

v3.2.1

### Feature type

Change to existing functionality

### Proposed functionality

Draw the device label text on top of the logical connection lines arrowheads, similar to like the text is drawn on top of the cables. One option could be to remove the arrowheads for logical connections.

### Use case

Should make the device labels easier to read.

### External dependencies

None

**Comment by dreng** [comment] 2023-01-29 14:12
Hi royvegard! Thanks for your contribution. This proposal would work against the logic of the vis-network framework, which we use to render all stuff. There's a few problems actually:

First of all, it is not possible to have any label on cable ends. Vis-network always renders optionally only one label in the middle of a connection. Please have a look at https://visjs.github.io/vis-network/examples/ to learn more about how vis-network is able to render. You are of course welcome to add a FR there.

The second problem is that you propose to render a text to a connection which belongs to a device instead renering it to the device itself. The algorithm loops through all devices and assigns a label which is taken from the device dataset. Cables are not calculated within another algorithm. We would need to determine the device's name a cable is connected to in order to place a name at the cable end. But what about all the other cables that are connected to that device? We would end in a name on each cable end which would become unreadable. It simply does ont scale at all just like I explained in #126.

Third problem is that vis-network always places the text underneath of icons. I think there is nothing we can do about that. As stated before, you are welcome to add a FR at their github place.

**Comment by royvegard** [comment] 2023-01-29 14:31
It seems I have not been clear in my original proposal. Maybe I could have made this a bug issue. I'll try to be more clear.

The problem is that the arrowheads of the logical connections are drawn above the labels of the devices.
![image](https://user-images.githubusercontent.com/54801/215332755-55553b73-a1d4-47da-b7b5-14730954e930.png)

My proposal is simply to avoid this so that the labels for the devices would be easier to read.

As you mention it looks like drawing arrow heads on top of text is just the way visjs works, so drawing the text on top of the arrows might not be so easy. The simplest way to fix this is to simply not draw arrow heads for logical connections. I don't think the arrow heads add any meaningful information, so I propose to just get rid of the arrow heads. And guess what - I have a patch for that too 😄

**Comment by dreng** [comment] 2023-01-29 14:46
Ah, okay. I See what you mean. When we discussed logical connections in #188 we came to a point where we found it difficult to distinguish between all the connection types. We already have dotted and dashed connections. That's why I proposed to add an arrow because that makes it very easy to differentiate. But I see your point. I don't want to decide this alone and ask @mattieserver and other users to tell their opinion. Maybe it helps to post an image of the patched version in order to make it easier to decide.

**Comment by royvegard** [comment] 2023-01-29 16:01
Oh, I didn't think about that the other edge types could be too similar. Mostly because I didn't have any power or circuit connections in my example.

One way to differentiate the edge types is to add single character edge labels like C for cable, W for wifi etc. Or use emoji characters 🔌 📡 🖧

![image](https://user-images.githubusercontent.com/54801/215338492-27cff137-4528-4888-b97b-dd6ecd695989.png)

**Comment by dreng** [comment] 2023-01-29 16:51
I've had a look at the situation with a very high zoom level. Obviously the dots are rendered underneath the labels while the arrows are rendered above. The current behavior was intended by the vis-network team. Fortunately the issue has been addressed there and has already been resolved. See https://github.com/visjs/vis-network/issues/883

So there might be a way to keep the arrows without covering the label. If that does not do the trick I also tend to get rid of the arrows.

**Comment by dreng** [comment] 2023-03-23 19:46
@royvegard May I assign this bug to you?

**Closed** 2023-04-02 19:38 UTC
Labels: type: bug, status: accepted
