### ISSUE TITLE
Attribute error on new install

### ISSUE THREAD

**Issue by andershagman** [mattieserver/netbox-topology-views#335] opened 2023-06-22 09:30 UTC
### NetBox version

v3.5.3

### Topology Views version

v3.5.0

### Steps to Reproduce

New install
Click...

![bild](https://github.com/mattieserver/netbox-topology-views/assets/20284974/e7d63006-8478-41c3-b2d4-72b0b3044671)

Click on topology

### Expected Behavior

Show topology

### Observed Behavior

![bild](https://github.com/mattieserver/netbox-topology-views/assets/20284974/1e6deb7d-b4be-485a-8339-6471496408ad)

**Comment by dreng** [comment] 2023-06-22 09:56
Duplicate of https://github.com/mattieserver/netbox-topology-views/issues/321 and already fixed in current beta.

**Closed by dreng** 2023-06-22 09:56 UTC
Labels: type: bug, status: duplicate
