### ISSUE TITLE
fix AttributeError: 'CircuitTermination' object has no attribute 'device'

### ISSUE THREAD

**Issue by mattieserver** [mattieserver/netbox-topology-views#23] opened 2020-05-19 20:13 UTC
when you enable the Circuit Termination you may see the following error:
`AttributeError: 'CircuitTermination' object has no attribute 'device'`
Also see #20

**Comment by mattieserver** [comment] 2020-05-20 06:11
@martydingo , can you check if you issue is resolved?

**Comment by mattieserver** [comment] 2020-05-20 06:12
#24 added more NoneType checks

**Comment by martydingo** [comment] 2020-05-20 07:42
Right, it's not erroring but I'm not seeing the circuit between a patch panel and a router, so it goes from router -> 24 LC patch panel (unnamed) then to a circuit, then lands at another DC on a router. 

I had to redact a fair amount here, sorry. 

![image](https://user-images.githubusercontent.com/49862656/82418750-494f3400-9a75-11ea-92ef-15583862d76a.png)

I'm expecting the red to display, and this would then connect our sites up.

![image](https://user-images.githubusercontent.com/49862656/82419059-c67aa900-9a75-11ea-8c07-ed1a017ab156.png)

**Comment by mattieserver** [comment] 2020-05-20 07:48
Thanks for the info, I understand that you have to redact some info.
I believe the 'issue' now is that i did not include any checks for patch panels.
I will check what if i can add support for patch panels.

**Comment by martydingo** [comment] 2020-05-20 10:08
Well people should be putting things like circuits into patch panels as
standard, unless it's just the one circuit being used as a WAN, that I can
understand.

Thanks very much!

**Comment by martydingo** [comment] 2020-06-01 06:51
Is there any progress on this?

**Comment by mattieserver** [comment] 2020-06-01 16:46
I did not find the time yet.

**Comment by Bah27** [comment] 2021-07-09 11:07
Hello ,
what is the difference between the colors on the edges.

**Comment by mattieserver** [comment] 2021-07-09 11:12
Nothing, it takes the colour you used for the cable in netbox itself.
Same with the devices, it takes the colour of the device role.

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden

________________________________

**Comment by Bah27** [comment] 2021-07-09 11:15
thank you for your quick response

**Comment by mskalecki** [comment] 2022-08-11 15:46
The plugin crashes with this exception if you have a cable with termination_a connected to a device and termination_b connected to a circuit.

This line is the culprit (it assumes that `link.termination_b.device` exists:
https://github.com/mattieserver/netbox-topology-views/blob/0b6df3bd2807df301cb660f953ed860ba996144f/netbox_topology_views/views.py#L163

The fix is to add the check:
`elif link.termination_a.device.id in device_ids and hasattr(link.termination_b, 'device') and link.termination_b.device.id in device_ids:`

**Comment by candlerb** [comment] 2022-10-19 19:14
I still get this problem with NTV 2.0.1 under Netbox 3.2.9:

```
...
Oct 19 19:02:23 noc gunicorn[1795]:   File "/opt/netbox-3.2.9/venv/lib/python3.10/site-packages/netbox_topology_views/views.py", line 291
, in get
Oct 19 19:02:23 noc gunicorn[1795]:     topo_data = get_topology_data(self.queryset, hide_unconnected, intermediate_dev_role_ids, end2end
_connections)
Oct 19 19:02:23 noc gunicorn[1795]:   File "/opt/netbox-3.2.9/venv/lib/python3.10/site-packages/netbox_topology_views/views.py", line 156
, in get_topology_data
Oct 19 19:02:23 noc gunicorn[1795]:     elif link.termination_a.device.id in device_ids and link.termination_b.device.id in device_ids:
Oct 19 19:02:23 noc gunicorn[1795]: AttributeError: 'CircuitTermination' object has no attribute 'device'
```

The fix given by @mskalecki prevents the error, thank you!

(OTOH I am not seeing any devices at all, regardless of what filters I select; but that's a different problem)

**Comment by candlerb** [comment] 2022-10-19 19:57
Actually that fix doesn't work in the following scenario:

* Device A interface A'
* --- cable --->
* CircuitTermination (A side)
* --- circuit C --->
* CircuitTermination (Z side)
* --- cable --->
* Device B interface B'

In this situation, with NTV 2.0.3, I find there is no link shown between device A and B, regardless of whether "Display end-to-end connections" is checked.

I'm not sure if such a circuit connection is *expected* to be shown, and if so, how it should be rendered. I notice the example image on the README.md page shows a dotted line, but I'm not sure if that's a circuit or something else.

**Comment by candlerb** [comment] 2023-01-07 19:19
I am testing git+https://github.com/mattieserver/netbox-topology-views@master now.

A few minor comments while I did this:
* I was a bit surprised at first to see all devices floating and unconnected. This is because neither "Show cables" nor "Show logical connections" is selected by default.  I think one of them should be active by default (probably "Show cables").  Some ideas:
    * It would perhaps be reasonable to invert this to "Hide cables", given that there's already "Hide unconnected".
    * Is it useful in practice to be able to show both cables and logical connections simultaneously, or topology without either type of connection?  If not, then this could simplify to a radio button pair.  Or even a single checkbox "show logical connections" which means "show logical connections instead of cables".
    * Otherwise, if you're keeping two checkboxes, I think it would be good if "Show cables" and "Show logical connections" were adjacent to each other
* When I select both "Hide connected" and "Show logical connections", for some reason the icons don't display:

![image](https://user-images.githubusercontent.com/44789/211166623-99ed9928-9909-432b-ad65-fb33d7fad800.png)
![image](https://user-images.githubusercontent.com/44789/211166652-a4e74873-e407-4783-8957-438ac29a57bd.png)

But without "Hide unconnected" it's fine:

![image](https://user-images.githubusercontent.com/44789/211166679-e935fed0-72e0-43ba-be79-d6bec37f2a58.png)

Now, back to the initial issue around circuits.  With "Show circuit terminations" and "Show Cables" (or "Show Logical Connections"), it's now working:

![image](https://user-images.githubusercontent.com/44789/211166745-d384e7b3-48dc-4476-a113-5514f054954b.png)

In fact, "Show circuit terminations" without either Show Cables or Show Logical Connections is also fine:

![image](https://user-images.githubusercontent.com/44789/211166790-fcc3b243-f70c-4cfc-a762-d80bbd914f94.png)

So I think this issue is good to close now - thank you!

**Comment by dreng** [comment] 2023-01-07 20:32
Thank you for your detailed feedback! I'm going to close this issue then.

All other things should be addressed in a seperate bug report, but just to give a quick feedback:
- Unconnected devices: This has been reported already regarding the topology button in "Sites" (#237 ). We could provide a very quick fix, but I'm planning to change some related parts anyway and therefore I leave it like it is for now.
- Hide cables: Disagree. I'd rather change "hide unconnected" to "show unconnected" in order to have the same logic in all checkboxes. See also #238.
- Show both: We discussed this in the PR #188 and finally left the decision to the user. Each combination might be useful. There's also a config file option "hide_single_cable_logical_conns" which prevents redundancy with cables and logical connections.

**Closed by dreng** 2023-01-07 20:32 UTC
Labels: type: bug, status: revisions needed

**Comment by dreng** [comment] 2023-01-07 20:48
>     * When I select both "Hide unconnected" and "Show logical connections", for some reason the icons don't display:

I wasn't able to reproduce this. My result if I tick both options:
![topo_hide_uncon](https://user-images.githubusercontent.com/20901110/211169742-2e7585dd-b246-47ac-ac65-51b35c345636.png)
